### ISSUE TITLE
Getting started with grommet on Ubuntu

### ISSUE THREAD

**Issue by Don-Altobello** [HewlettPackard/grommet#163]
When I follow the steps as described on http://grommet.io/docs/develop/get-started
 the step
 `grommet init sample-app`
Freezes after a while.  The cursor keeps spinning forever.
![image](https://cloud.githubusercontent.com/assets/12054354/9383450/6f245676-4749-11e5-848d-f9ca230f6a67.png)

`my OS: Ubuntu precise (12.04.3 LTS)`

`developer@cwb-dev:~/UX/sample-app$ node -v
v0.12.7`

`developer@cwb-dev:~/UX/sample-app$ npm -v
2.13.5`

`developer@cwb-dev:~/UX/sample-app$ gulp -v
[14:48:46] CLI version 3.9.0
[14:48:46] Local version 3.9.0
`

**Comment by alansouzati** [comment]
Hi @Don-Altobello thanks for reporting this. I don't see anything wrong with your installation. It takes time initially because all the dependencies needs to be downloaded from the NPM central repository. Once you have local cache, installation will be much faster. I would suggest installing again and report back in case you get any error logs.

**Comment by Don-Altobello** [comment]
@alansouzati  ,
Thanks for the advice. Today I installed all components again and let it run for a couple of hours. I might have been too impatient before caused by the scripting which doesn't show progress.
Today I have a working grommet setup.
