### ISSUE TITLE
[people-finder] project issues with eslint

### ISSUE THREAD

**Issue by rtspotts** [HewlettPackard/grommet#168]
Installed the people finder example app using 'grommet init people-finder' and ran 'npm install' in the people-finder directory.  When trying to get the dev environment running with 'gulp dev' there is an error thrown in the eslint process:

Error: Definition for rule 'react/jsx-max-props-per-line' was not found.
at C:\Users\RTS\Grommet_Apps\people-finder\node_modules\eslint\lib\eslint.js
:647:27

Commenting the lines:   

  73:  react/jsx-max-props-per-line: 1
  74:  react/jsx-no-duplicate-props: 1

in **people-finder/node_modules/grommet/utils/gulp/eslintrc** clears up the problem.  It appears that the rules above are not supported by the eslint and eslint-plugin-react versions specified in the package.json file supplied in the example.

**Comment by alansouzati** [comment]
Thanks @rtspotts for submitting this. 

If you are using Grommet version `< 0.3.2` then your package.json has the dependency set like this:

```
  dependencies: {
    "grommet": "https://github.com/HewlettPackard/grommet.git#stable"
  }
```

This means that we are using the latest stable branch (every commit that passed the CI build). As we are in early stages, this is sometimes extremely useful because it allows you to get the latest bits from Grommet without waiting for an actual release.

At the same time, this is problematic because of conflicting changes. 

This is the issue you are facing, the latest stable branch had a change that conflicted with your version of eslint, as you pointed out.

There are a couple of fixes possible for this:

### Update grommet

Recommended

```
$ npm update -g grommet
$ grommet --version //0.3.2
$ grommet init people-finder
```

### Update library dependencies

```
  dependencies: {
    "grommet": "https://github.com/HewlettPackard/grommet.git#stable"
  },
  devDependencies: {
    ...
    "gulp-eslint": "^1.0.0",
    "eslint": "^1.1.0",
    "eslint-plugin-react": "^3.2.3",
    ...
  }
```

then run `npm update` inside people-finder

### Use a fixed Grommet version in your package.json:

```
  dependencies: {
    "grommet": "0.3.1"
  }
```

then run `npm update` inside people-finder

Please let us know if any of these fixes worked for you.

**Comment by alansouzati** [comment]
Hi @rtspotts any news here?

**Comment by rtspotts** [comment]
Hi @alansouzati, your info above got me sorted, thanks.
