### ISSUE TITLE
unable to access web page from network (non 127.0.0.1)

### ISSUE THREAD

**Issue by samogami** [HewlettPackard/grommet#47]
1. Followed the npm instructions on [grommet Getting Started](http://grommet.io/docs/documentation/get-started) page.
2. Ran __gulp dev__
3. Everything works fine from the command line, can access the webpage from local computer. I am not able to access the webpage from a remote computer browser.

I have also tested this on the server running grommet and can connect successfully connect with  __telnet 127.0.0.1 9000__ but  __telnet *hostname* 9000__ I get Error Connection refused.

**Comment by alansouzati** [comment]
Hi,

  Thanks for finding this issue. It turns out that `gulp dev` was only listening to **localhost**.

  I've added `devServerHost` key to the gulpfile `opts`. Use that key to specify a different host rather than localhost (e.g. the IP address of the remote machine you are trying to access).

  This will be part of Grommet 0.2.5, if you want to have early access to this configuration open your `package.json` and update `grommet` dependency to the latest stable branch.

```javascript
{
   ...
   "dependencies": {
     "grommet": "https://github.com/HewlettPackard/grommet.git#stable",
   }
   ...
}
```

Let me know if that works for you.

**Comment by alansouzati** [comment]
Hey @samogami did you have a change to validate the fix for this issue?

**Comment by samogami** [comment]
Not yet working on getting grommet 0.2.5 to work first.

**Comment by alansouzati** [comment]
Hey sam, could you please try with 0.3.0? I believe this should be working now.

**Comment by samogami** [comment]
This works now for me.
