### ISSUE TITLE
Bower broken font path

### ISSUE THREAD

**Issue by mattfarina** [HewlettPackard/grommet#72]
The font path in the css files begins with a `~`. For example `~grommet/scss/hpinc/font/hps-me-w27-regular-woff.woff`.

**Comment by alansouzati** [comment]
Thanks for reporting that, we have it fixed in the master now, it should be part of the next version. In the mean time you can use the fonts CDN paths:

**Metric font**: http://hpefonts.s3.amazonaws.com/MetricWeb-Regular.woff
 
**HPSimplified font**: http://hpincfonts.s3.amazonaws.com/hps-me-w27-regular-woff.woff

**Comment by mattfarina** [comment]
I'm a sucker for _https_. It might be worth updating those URLs for the default. Especially if an app is going to be used behind https. Just thinking of a sane default.

**Comment by alansouzati** [comment]
Fixed by #76.
